jobs:
  - job: macOS_build
    displayName: macOS build
    dependsOn: GetReleaseVersion
    timeoutInMinutes: 180

    variables:
      ReleaseVersion: $[ dependencies.GetReleaseVersion.outputs['Version.ReleaseVersion'] ]
      IsReleaseBranch: $[ dependencies.GetReleaseVersion.outputs['Version.IsReleaseBranch'] ]
      IsSignedZipBranch: $[ dependencies.GetReleaseVersion.outputs['Version.IsSignedZipBranch'] ]
    pool:
      vmImage: macos-10.14

    steps:
      - template: templates/macos-preparation.yml

      - template: templates/cache.yml
        parameters:
          OS: macos

      - template: templates/macos-bootstrap.yml

      - script: script/lint
        displayName: Run linter

      - template: templates/macos-build.yml

      - script: |
          cp $(Build.SourcesDirectory)/out/*.zip $(Build.ArtifactStagingDirectory)
        displayName: Stage Artifacts

      - template: templates/publish.yml
        parameters:
          artifacts:
            - filename: atom-mac.zip
              dir: $(Build.ArtifactStagingDirectory)
              condition: succeeded()
            - filename: atom-mac-symbols.zip
              dir: $(Build.ArtifactStagingDirectory)
              condition: succeeded()
            - filename: atom-api.json
              dir: $(Build.SourcesDirectory)/docs/output
              condition: succeeded()

  - job: macOS_tests
    displayName: macOS test
    dependsOn: macOS_build
    timeoutInMinutes: 180
    pool:
      vmImage: macos-10.14
    strategy:
      maxParallel: 3
      matrix:
        core:
          RunCoreTests: true
          RunPackageTests: false
        packages-1:
          RunCoreTests: false
          RunPackageTests: 1
        packages-2:
          RunCoreTests: false
          RunPackageTests: 2

    steps:
      - template: templates/macos-preparation.yml

      - template: templates/cache.yml
        parameters:
          OS: macos

      # The artifact caching task does not work on forks, so we need to
      # bootstrap again for pull requests coming from forked repositories.
      - template: templates/macos-bootstrap.yml

      - template: templates/macos-test.yml
