jobs:
  - job: Windows
    dependsOn: GetReleaseVersion
    timeoutInMinutes: 180
    strategy:
      maxParallel: 2
      matrix:
        x64:
          buildArch: x64
        x86:
          buildArch: x86

    pool:
      vmImage: vs2017-win2016

    variables:
      AppName: $[ dependencies.GetReleaseVersion.outputs['Version.AppName'] ]
      ReleaseVersion: $[ dependencies.GetReleaseVersion.outputs['Version.ReleaseVersion'] ]
      IsReleaseBranch: $[ dependencies.GetReleaseVersion.outputs['Version.IsReleaseBranch'] ]
      IsSignedZipBranch: $[ dependencies.GetReleaseVersion.outputs['Version.IsSignedZipBranch'] ]

    steps:
      - template: templates/windows-preparation.yml

      - template: templates/cache.yml
        parameters:
          OS: windows

      - template: templates/bootstrap.yml

      - script: node script\vsts\windows-run.js script\lint.cmd
        env:
          BUILD_ARCH: $(buildArch)
        displayName: Run linter

      - template: templates/windows-build.yml

      - template: templates/windows-test.yml

      - script: |
          IF [%BUILD_ARCH%]==[x64] (
            SET FileID=-x64
          ) ELSE (
            SET FileID=
          )
          echo FileID set to: %FileID%
        env:
          BUILD_ARCH: $(buildArch)
        displayName: Set FileID based on the arch

      - template: templates/publish.yml
        parameters:
          artifacts:
            - filename: atom$(FileID)-windows.zip
              dir: $(Build.SourcesDirectory)/out
              condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
            - filename: AtomSetup$(FileID).exe
              dir: $(Build.SourcesDirectory)/out
              condition: and(succeeded(), eq(variables['IsReleaseBranch'], 'true'))
            - filename: $(AppName)$(FileID)-$(ReleaseVersion)-full.nupkg
              dir: $(Build.SourcesDirectory)/out
              condition: and(succeeded(), eq(variables['IsReleaseBranch'], 'true'))
            - filename: $(AppName)$(FileID)-$(ReleaseVersion)-delta.nupkg
              dir: $(Build.SourcesDirectory)/out
              condition: and(succeeded(), eq(variables['IsReleaseBranch'], 'true'))
              continueOnError: true # Nightly builds don't produce delta packages yet, so don't fail the build
            - filename: RELEASES$(FileID)
              dir: $(Build.SourcesDirectory)/out
              condition: and(succeeded(), eq(variables['IsReleaseBranch'], 'true'))
