jobs:
  - job: Windows
    dependsOn: GetReleaseVersion
    timeoutInMinutes: 180
    strategy:
      maxParallel: 2
      matrix:
        x64:
          buildArch: x64
        x86:
          buildArch: x86

    pool:
      vmImage: vs2017-win2016

    variables:
      AppName: $[ dependencies.GetReleaseVersion.outputs['Version.AppName'] ]
      ReleaseVersion: $[ dependencies.GetReleaseVersion.outputs['Version.ReleaseVersion'] ]
      IsReleaseBranch: $[ dependencies.GetReleaseVersion.outputs['Version.IsReleaseBranch'] ]
      IsSignedZipBranch: $[ dependencies.GetReleaseVersion.outputs['Version.IsSignedZipBranch'] ]

    steps:
      - template: templates/windows-preparation.yml

      - template: templates/cache.yml
        parameters:
          OS: windows

      - template: templates/windows-bootstrap.yml

      - script: node script\vsts\windows-run.js script\lint.cmd
        env:
          BUILD_ARCH: $(buildArch)
        displayName: Run linter

      - template: templates/windows-build.yml

      - template: templates/windows-test.yml

      - template: templates/windows-publish.yml
