trigger: none # No CI builds, only PR builds

jobs:
  - job: GetReleaseVersion
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          cd script/vsts
          npm ci
          node get-release-version.js
        name: Version

  # Import OS-specific build definitions
  - template: platforms/windows.yml
  - template: platforms/macos.yml
  - template: platforms/linux.yml
